firstWebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls'))
]

music/urls.py
# from django.urls import path, re_path
from django.conf.urls import url
from . import views

app_name = "music"

urlpatterns = [
    # http://127.0.0.1:8000/music/
    url(r'^$', views.IndexView.as_view(), name="index"), # based home page
    # url(r'^$', views.index, name="index"), # based home page

    # http://127.0.0.1:8000/music/<album_id> 
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name = "display_album"),
    # url(r'^(?P<album_id>[0-9]+)/$', views.detail, name = "display_album"),

    # http://127.0.0.1:8000/music/<album_id>/favorite
    url(r'^(?P<album_id>[0-9]+)/favorite$', views.favorite, name = "favorite"),

    # music/album/add
    url(r'album/add/$', views.AlbumCreate.as_view, name = 'album_add'),


]

music/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Album(models.Model) :
    artist = models.CharField (max_length = 250)
    title = models.CharField (max_length = 250)
    genre = models.CharField (max_length = 100)
    album_logo = models.CharField (max_length = 500)   #urls

    # def get_absolute_url(self):
    #     return reverse('music:detail', kwargs={'pk' : self.pk})

    def __str__(self):
        return self.title + " - " + self.artist


class Song(models.Model) :
    album = models.ForeignKey(Album, on_delete = models.CASCADE)
    file_type = models.CharField(max_length = 10)
    song_title = models.CharField(max_length = 250)
    is_favorite =models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        fields = ['username', 'email', 'password']

music/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login
from django.template import loader
from django.http import HttpResponse
from .models import Album, Song
from django.http import Http404
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import View
from .forms import UserForm

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_album'

    def get_queryset(self):
        return Album.objects.all()

# def index(request) :
#     all_album = Album.objects.all()
#     template = loader.get_template('music/index.html')
#     context = {
#         "all_album" : all_album,
#     }
#     return HttpResponse(template.render(context, request))
#     # return render(request, 'music/index.html', context)



class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'

# def detail(request, album_id) :
#     # try:
#     #     album = Album.objects.get(pk = album_id)
#     # except Album.DoesNotExist:
#     #     raise Http404("Album Does Not Exist")
#
#     album = get_object_or_404(Album, pk=album_id)
#     return render(request, 'music/detail.html', {'album' : album})



def favorite(request, album_id):
    album = get_object_or_404(Album, pk = album_id)
    try:
        selected_song = album.song_set.get(pk=request.POST["song"])
    except(KeyError, Song.DoesNotExist):
        return (request, 'music/detail.html'), {
            'album' : album,
            "error_msg" : "Song not valid",
        }
    else:
        selected_song.is_favorite = True
        selected_song.save()
        return render(request, 'music/detail.html', {'album': album})


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'title', 'genre', 'album_logo']

music/templates/music/album_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Album - Add</title>
</head>
<body>
{% extends 'music/base.html' %}
{% block title %} Music {% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success"> Submit </button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

</body>
</html>

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> First - Webpage </title>

    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css'%}"/>
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"/>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>

</head>
<body>
    <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <!-- header -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="topNavBar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
{#                        <span class="navbar-toggler-icon"></span>#}
                    </button>
                    <a class="navbar-brand" href="{% url 'music:index' %}"> {% block title %} Main {% endblock %} </a>
                </div>

                <!-- items -->
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav" id="topNavBar">
                        <li class="active">
                            <a href="{% url 'music:index' %}">
                                <span class="glyphicon glyphicon-cd" aria-hidden="true"></span> &nbsp;
                                Albums
                            </a>
                        </li>

                        <li class="">
                            <a href="#Song">
                                <span class="glyphicon glyphicon-music" aria-hidden="true"></span> &nbsp;
                                Songs
                            </a>
                        </li>
                    </ul>

                    <form class="navbar-form navbar-left" role="search" method="get" action="#">
                        <div class="form-group">
                            <input type="text" class="form-control" name="q" value="">
                            <button type="submit" class="btn btn-default"> Search </button>
                        </div>
                    </form>

                    <ul class="nav navbar-nav navbar-right">
                        <li class="">
                            <a href="{% url 'music:album_add' %}">
                                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> &nbsp;
                                Add Album
                            </a>
                        </li>

                        <li class="">
                            <a href="#Logout">
                                <span class="glyphicon glyphicon-off" aria-hidden="true"></span> &nbsp;
                                Logout
                            </a>
                        </li>
                    </ul>

                </div>

            </div>
    </nav>

    {% block body%}
    {% endblock %}

</body>
</html>

music/templates/music/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Album Detail(Favorite) Page</title>
</head>
<body>
    {% extends 'music/base.html' %}
    {% block title %} Detail {% endblock %}

    {% block body %}
        <h1> Album: {{ album.title }} </h1>
        <img src="{{ album.album_logo }}">
        <h3> Artist: {{ album.artist }}</h3>

        {%  if error_msg %}
            <p><strong>{{ error_msg }}</strong></p>
        {% endif %}

        <form action="{%  url 'music:favorite' album.id %}" method="post">
            {% csrf_token %}

            {% for song in album.song_set.all %}
                <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}" />
                <label for="song{{ forloop.counter }}">
                    {{ song.song_title }}
                        {%  if song.is_favorite %}
                            <img src="http://i.imgur.com/b9b13Rd.png"/>
                        {% endif %}
                </label> <br>
            {% endfor %}

            <input type="submit" value="Favorite!">
{#            <input type="submit" value="Unfavorite :(">#}
        </form>

{#            <ul>#}
{#                {% for song in album.song_set.all %}#}
{#                    <li>{{ song.song_title }} - {{ song.file_type }}</li>#}
{#                {% endfor %}#}
{#            </ul>#}
    {% endblock %}




</body>
</html>

music/templates/music/form-template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details - Template</title>
</head>
<body>
    {% for fields in form %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <span class="text-danger small"> {{ field.errors }} </span>
            </div>
        </div>

        <label class="control-lable col-sm"> {{ field.label_tag }}</label>
        <div class="col-sm-10"> {{ field }} </div>
    {% endfor %}
</body>
</html>

music/templates/music/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Music - Home Page</title>
</head>

<body>
{% extends 'music/base.html' %}
{% block title %} Music {% endblock %}

    {% block body %}
        <h3> Album List</h3>
        {% if all_album %}
            <ul>
                {% for album in all_album %}
    {#                <li><a href="{{ album.id }}/"> {{ album.title }} </a> </li>#}
                    <li><a href="{%  url 'music:display_album' album.id %}"> {{ album.title }} </a> </li>
                {% endfor %}
            </ul>
        {% else %}
            <h3> Library is empty </h3>
        {% endif %}
    {% endblock %}
</body>

</html>